# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rahimiabdulrahmanab/Clinics-Dashboard/blob/main/app.ipynb
"""

import pandas as pd

# URL of your clinics CSV
url = "https://raw.githubusercontent.com/rahimiabdulrahmanab/Clinics-Dashboard/main/Clinics.csv"

# Load the CSV into a pandas DataFrame
df = pd.read_csv(url)

# Show the first 5 rows
df.head()

import folium
from streamlit_folium import st_folium
import streamlit as st


# Sidebar for filtering
st.sidebar.header("Filter Clinics")

# Add "All" to the list of provinces
provinces = ["All"] + list(df['Province Name'].unique())

# Dropdown to select province
selected_province = st.sidebar.selectbox("Select Province", provinces)

# Filter data
if selected_province == "All":
    filtered_df = df
else:
    filtered_df = df[df['Province Name'] == selected_province]

# Determine map center and zoom
if not filtered_df.empty:
    # Center on mean latitude/longitude
    center_lat = filtered_df['Latitude'].mean()
    center_lon = filtered_df['Longitude'].mean()
    # Zoom in closer if single province, farther if All
    zoom_level = 7 if selected_province != "All" else 6
else:
    center_lat = 34.5
    center_lon = 69.2
    zoom_level = 6

# Create map
af_map = folium.Map(location=[center_lat, center_lon], zoom_start=zoom_level)

# Add markers for filtered clinics
for _, row in filtered_df.iterrows():
    popup_html = f"""
    <table style="border-collapse: collapse; width: 200px;">
      <tr><th colspan="2" style="text-align:center; background-color:#f2f2f2;">{row['Facility Name (DHIS2)']}</th></tr>
      <tr><td style="border:1px solid black; padding:3px;">Province</td><td style="border:1px solid black; padding:3px;">{row['Province Name']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">District</td><td style="border:1px solid black; padding:3px;">{row['District Name']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">Facility Type</td><td style="border:1px solid black; padding:3px;">{row['Facility Type']}</td></tr>
    </table>
    """
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_html,
        tooltip=row['Facility Name (DHIS2)'],
        icon=folium.Icon(color='blue', icon='hospital', prefix='fa')
    ).add_to(af_map)

# Display map in Streamlit
st_data = st_folium(af_map, width=800, height=600)

