# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rahimiabdulrahmanab/Clinics-Dashboard/blob/main/app.ipynb
"""

import pandas as pd

# URL of your clinics CSV
url = "https://raw.githubusercontent.com/rahimiabdulrahmanab/Clinics-Dashboard/main/Clinics.csv"

# Load the CSV into a pandas DataFrame
df = pd.read_csv(url)

# Show the first 5 rows
df.head()

import streamlit as st
import pandas as pd
import folium
from streamlit_folium import st_folium

# 1️⃣ Set page title
st.set_page_config(page_title="Afghanistan Clinics Dashboard", layout="wide")

# 2️⃣ Load CSV from GitHub
url = "https://raw.githubusercontent.com/rahimiabdulrahmanab/Clinics-Dashboard/main/Clinics.csv"
df = pd.read_csv(url)

# 3️⃣ Create Folium map
af_map = folium.Map(location=[34.5, 69.2], zoom_start=6)

# 4️⃣ Add markers with table popups
for _, row in df.iterrows():
    popup_html = f"""
    <table style="border-collapse: collapse; width: 200px;">
      <tr><th colspan="2" style="text-align:center; background-color:#f2f2f2;">{row['Facility Name (DHIS2)']}</th></tr>
      <tr><td style="border:1px solid black; padding:3px;">Province</td><td style="border:1px solid black; padding:3px;">{row['Province Name']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">District</td><td style="border:1px solid black; padding:3px;">{row['District Name']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">Facility Type</td><td style="border:1px solid black; padding:3px;">{row['Facility Type']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">Latitude</td><td style="border:1px solid black; padding:3px;">{row['Latitude']}</td></tr>
      <tr><td style="border:1px solid black; padding:3px;">Longitude</td><td style="border:1px solid black; padding:3px;">{row['Longitude']}</td></tr>
    </table>
    """

    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        popup=popup_html,
        tooltip=row['Facility Name (DHIS2)'],
        icon=folium.DivIcon(html='<div style="font-size:12px; color:red;">&#10010;</div>')
    ).add_to(af_map)

# 5️⃣ Display map in Streamlit
st_data = st_folium(af_map, width=800, height=600)

# Sidebar for filtering
st.sidebar.header("Filter Clinics")

# Get unique provinces from the data
provinces = df['Province Name'].unique()

# Dropdown for selecting a province
selected_province = st.sidebar.selectbox("Select Province", provinces)

# Filter data based on selection
filtered_df = df[df['Province Name'] == selected_province]

